import * as path from "path";
import { fileURLToPath } from "url";
import TestRunner, { Transformer } from "./TestRunner.js";
import { buildSchema, graphql, GraphQLSchema, printSchema } from "graphql";
import { Command } from "commander";
import { readFileSync } from "fs";
import { diff } from "jest-diff";
import { SEMANTIC_NON_NULL_DIRECTIVE } from "../publicDirectives.js";
import { Result, ok } from "../utils/Result.js";
import { writeTypeScriptTypeToDisk } from "../../scripts/buildConfigTypes.js";
import { Markdown } from "./Markdown.js";

writeTypeScriptTypeToDisk();

const program = new Command();

program
  .name("grats-tests")
  .description("Run Grats' internal tests")
  .option(
    "-w, --write",
    "Write the actual output of the test to the expected output files. Useful for updating tests.",
  )
  .option(
    "-f, --filter <FILTER_REGEX>",
    "A regex to filter the tests to run. Only tests with a file path matching the regex will be run.",
  )
  .option("-i, --interactive", "Run tests in interactive mode.")
  .action(async ({ filter, write, interactive }) => {
    const filterRegex = filter ?? null;
    let failures = false;
    for (const {
      fixturesDir,
      transformer,
      testFilePattern,
      ignoreFilePattern,
    } of testDirs) {
      const runner = new TestRunner(
        fixturesDir,
        !!write,
        filterRegex,
        testFilePattern,
        ignoreFilePattern,
        transformer,
      );
      failures = !(await runner.run({ interactive })) || failures;
    }
    if (failures) {
      process.exit(1);
    }
  });

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const integrationFixturesDir = path.join(__dirname, "integrationFixtures");

type TestDir = {
  fixturesDir: string;
  testFilePattern: RegExp;
  ignoreFilePattern: RegExp | null;
  transformer: Transformer;
};

const testDirs: TestDir[] = [
  {
    fixturesDir: integrationFixturesDir,
    testFilePattern: /index.ts$/,
    ignoreFilePattern: /\/(schema\.(ts|graphql)|enums\.ts)$/,
    transformer: async (
      _code: string,
      fileName: string,
    ): Promise<Result<Markdown, Markdown> | false> => {
      // The schema files are generated by `cargo test --test fixtures`.
      const filePath = `${integrationFixturesDir}/${fileName}`;
      const schemaPath = path.join(path.dirname(filePath), "schema.ts");
      const sdlPath = path.join(path.dirname(filePath), "schema.graphql");

      const server = await import(filePath);

      if (server.query == null || typeof server.query !== "string") {
        throw new Error(
          `Expected \`${filePath}\` to export a query text as \`query\``,
        );
      }

      const schemaModule = await import(schemaPath);

      const actualSchema = schemaModule.getSchema(server.schemaConfig);

      const schemaDiff = compareSchemas(
        actualSchema,
        buildSchema(readFileSync(sdlPath, "utf8")),
      );

      if (schemaDiff) {
        console.log(schemaDiff);
        // TODO: Make this an actual test failure, not an error
        throw new Error("The codegen schema does not match the SDL schema.");
      }

      const data = await graphql({
        schema: actualSchema,
        source: server.query,
        variableValues: server.variables,
      });

      const markdown = new Markdown();
      markdown.addHeader(3, "Query Result");
      markdown.addCodeBlock(JSON.stringify(data, null, 2), "json");

      return ok(markdown);
    },
  },
];

// Returns null if the schemas are equal, otherwise returns a string diff.
function compareSchemas(
  actual: GraphQLSchema,
  expected: GraphQLSchema,
): string | null {
  const actualSDL = printSDLFromSchemaWithoutDirectives(actual);
  const expectedSDL = printSDLFromSchemaWithoutDirectives(expected);

  if (actualSDL === expectedSDL) {
    return null;
  }

  return diff(expectedSDL, actualSDL);
}

function printSDLFromSchemaWithoutDirectives(schema: GraphQLSchema): string {
  return printSchema(
    new GraphQLSchema({
      ...schema.toConfig(),
      directives: schema.getDirectives().filter((directive) => {
        return directive.name !== SEMANTIC_NON_NULL_DIRECTIVE;
      }),
    }),
  );
}

program.parse();
