[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
license = "MIT"
publish = false

[workspace.dependencies]
graphql_js = { path = "crates/graphql_js" }
grats = { path = "crates/grats" }
indexmap = "2"
oxc_allocator = "0.152"
oxc_ast = "0.152"
oxc_codegen = "0.152"
oxc_span = "0.152"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
