import express from "express";
import { graphqlHTTP } from "express-graphql";
import { getSchema } from "./schema"; // Generated by Grats

// Maps id to User object
var fakeDatabase = {
  a: { id: "a", name: "alice" },
  b: { id: "b", name: "bob" },
};

/** @gqlType */
type User = {
  /** @gqlField */
  id: string;
  /** @gqlField */
  name: string;
};

/** @gqlType */
type Query = unknown;

/** @gqlField */
export function user(_: Query, args: { id: string }): User {
  return fakeDatabase[args.id];
}

var app = express();
app.use(
  "/graphql",
  graphqlHTTP({
    schema: getSchema(),
    graphiql: true,
  }),
);
app.listen(4000);
console.log("Running a GraphQL API server at localhost:4000/graphql");
