import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import { makeTypeScriptType } from "../src/gratsConfig.js";
import { GratsConfigSpec } from "../src/configSpec.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export function writeTypeScriptTypeToDisk(): void {
  const doc = `/**
 * This file is generated by src/gratsConfigBeta.ts. Do not edit directly.
 * Run \`pnpm run test\` to regenerate.
 */

/**
 * Describes the shape of the Grats config after parsing, validation, and
 * defaults.
 */
${makeTypeScriptType(GratsConfigSpec)}
`;
  const outPath = path.join(__dirname, "TGratsConfig.ts");
  fs.writeFileSync(outPath, doc, "utf8");
}
