import * as fs from "fs";
import * as path from "path";
import { makeTypeScriptType } from "../src/gratsConfig";
import { GratsConfigSpec } from "../src/configSpec";

export function writeTypeScriptTypeToDisk(): void {
  const doc = `/**
 * This file is generated by src/gratsConfigBeta.ts. Do not edit directly.
 * Run \`pnpm run test\` to regenerate.
 */

/**
 * Describes the shape of the Grats config after parsing, validation, and
 * defaults.
 */
${makeTypeScriptType(GratsConfigSpec)}
`;
  const outPath = path.join(__dirname, "../src/TGratsConfig.ts");
  fs.writeFileSync(outPath, doc, "utf8");
}
