import { execFileSync } from "child_process";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

/**
 * Compiles the Rust port of Grats (`grats-rs/`) to WebAssembly and embeds it
 * in `src/rs/wasm.generated.ts`, from which `src/rs/load.ts` instantiates it.
 *
 * Embedding the module as base64 lets it load synchronously, and without any
 * bundler configuration, in both Node and the playground's web worker.
 */

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const workspaceDir = path.join(root, "grats-rs");
const targetDir =
  process.env.CARGO_TARGET_DIR ?? path.join(workspaceDir, "target");

execFileSync(
  "cargo",
  [
    "build",
    "--release",
    "--target",
    "wasm32-unknown-unknown",
    "--package",
    "grats_wasm",
  ],
  { cwd: workspaceDir, stdio: "inherit" },
);

const wasm = fs.readFileSync(
  path.join(targetDir, "wasm32-unknown-unknown", "release", "grats_wasm.wasm"),
);

fs.writeFileSync(
  path.join(root, "src", "rs", "wasm.generated.ts"),
  `// Generated by scripts/buildWasm.ts. Do not edit.
export const wasmBase64: string = "${wasm.toString("base64")}";
`,
);
