/**
 * Executable schema generated by Grats (https://grats.capt.dev)
 * Do not manually edit. Regenerate by running `npx grats`.
 * @generated
 */
import { greetings as queryGreetingsResolver } from "./app/api/graphql/query";
import { GraphQLSchema, GraphQLObjectType, GraphQLString } from "graphql";
const QueryType: GraphQLObjectType = new GraphQLObjectType({
    name: "Query",
    fields() {
        return {
            greetings: {
                name: "greetings",
                type: GraphQLString,
                resolve(source) {
                    return queryGreetingsResolver(source);
                }
            }
        };
    }
});
const schema = new GraphQLSchema({
    query: QueryType
});
export { schema };
