/**
 * Executable schema generated by Grats (https://grats.capt.dev)
 * Do not manually edit. Regenerate by running `npx grats`.
 */

import { Color as ColorEnum, Priority as PriorityEnum } from "./index";
export const enums = {
    Color: ColorEnum,
    Priority: PriorityEnum
};
export { ColorEnum as Color };
export { PriorityEnum as Priority };
